# -*- coding: utf-8 -*-
"""predict_and_send.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JKxhNSwtelLlY8bifOctmEp6RiVgxKp
"""

from google.colab import drive
drive.mount('/content/drive')



import pandas as pd
import requests
import time
from datetime import datetime, timedelta

# Load
df = pd.read_csv('/content/drive/MyDrive/predicted_with_aqi_ready.csv')

# URL
url = 'https://aqi-prediction.azurewebsites.net/insert_data_predict'

headers = {
    "Content-Type" : "application/json"
}

# กำหนดเวลาจุดเริ่มต้น
start_time = datetime(2025, 4, 29, 0, 0, 0)  # เริ่ม 29 เมษายน 00:00 น.

for index, row in df.iterrows():
    if row.isnull().any():
        print(f"Row {index+1} มี NaN - ข้าม")
        continue

    # สร้าง Timestamp ของแถวนั้น
    timestamp = start_time + timedelta(hours=index)
    timestamp_str = timestamp.strftime('%Y-%m-%d %H:%M:%S')

    # บังคับแปลง numpy.float64 → float ธรรมดา
    payload = {
        "timestamp": timestamp_str,  # ✅ เพิ่ม timestamp เข้า payload
        "predict_pm25": float(row['predict_pm25']),
        "predict_pm10": float(row['predict_pm10']),
        "predict_no2": float(row['predict_no2']),
        "predict_co": float(row['predict_co']),
        "predict_so2": float(row['predict_so2']),
        "predict_o3": float(row['predict_o3']),
        "predict_aqi": float(row['predict_aqi']),
        "predict_temp": float(row['predict_temp']),
        "predict_hum": float(row['predict_hum'])
    }

    print(f"Sending payload: {payload}")  # ✅ ดูก่อนว่าตรง

    response = requests.post(url, headers=headers , json=payload)


    print(f"Sent row {index+1} - Status: {response.status_code}")
    print(response.text)

    time.sleep(1)